CREATE TABLE "users" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar,
  "email" varchar UNIQUE,
  "phone" varchar UNIQUE,
  "password" varchar,
  "role" varchar,
  "is_active" boolean DEFAULT true,
  "created_at" timestamp,
  "updated_at" timestamp
);

CREATE TABLE "otp_verifications" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "identifier" varchar,
  "code" varchar,
  "type" varchar,
  "attempt_count" int DEFAULT 0,
  "expires_at" timestamp,
  "verified_at" timestamp,
  "created_at" timestamp
);

CREATE TABLE "profiles" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" int UNIQUE,
  "bio" text,
  "location" varchar,
  "avatar_url" varchar,
  "created_at" timestamp,
  "updated_at" timestamp
);

CREATE TABLE "skills" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar UNIQUE
);

CREATE TABLE "interests" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar UNIQUE
);

CREATE TABLE "user_skills" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" int,
  "skill_id" int
);

CREATE TABLE "user_interests" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" int,
  "interest_id" int
);

CREATE TABLE "events" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "organizer_id" int,
  "title" varchar,
  "description" text,
  "location" varchar,
  "quota" int,
  "start_date" date,
  "end_date" date,
  "status" varchar,
  "approved_by" int,
  "approved_at" timestamp,
  "impact_metric_template" varchar,
  "created_at" timestamp,
  "updated_at" timestamp
);

CREATE TABLE "event_skills" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "event_id" int,
  "skill_id" int
);

CREATE TABLE "event_interests" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "event_id" int,
  "interest_id" int
);

CREATE TABLE "applications" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" int,
  "event_id" int,
  "status" varchar,
  "attended" boolean DEFAULT false,
  "impact_value" numeric,
  "applied_at" timestamp,
  "completed_at" timestamp
);

CREATE TABLE "impact_logs" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "application_id" int,
  "metric_label" varchar,
  "value" numeric,
  "unit" varchar,
  "ai_headline" text,
  "created_at" timestamp
);

CREATE TABLE "skill_progress" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" int,
  "skill_id" int,
  "xp_total" int DEFAULT 0,
  "level" int DEFAULT 1,
  "updated_at" timestamp
);

CREATE TABLE "feedbacks" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" int,
  "event_id" int,
  "rating" int,
  "review" text,
  "created_at" timestamp
);

CREATE TABLE "points" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" int UNIQUE,
  "total_points" int DEFAULT 0,
  "updated_at" timestamp
);

CREATE TABLE "point_transactions" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" int,
  "event_id" int,
  "amount" int,
  "reason" varchar,
  "created_at" timestamp
);

CREATE TABLE "certificates" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "application_id" int,
  "user_id" int,
  "event_id" int,
  "file_url" varchar,
  "issued_at" timestamp
);

CREATE TABLE "notifications" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" int,
  "title" varchar,
  "message" text,
  "type" varchar,
  "entity_type" varchar,
  "entity_id" int,
  "is_read" boolean DEFAULT false,
  "created_at" timestamp
);

CREATE TABLE "audit_logs" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "actor_id" int,
  "action" varchar,
  "entity_type" varchar,
  "entity_id" int,
  "metadata" text,
  "ip_address" varchar,
  "created_at" timestamp
);

COMMENT ON COLUMN "users"."role" IS 'volunteer | organizer | admin';

COMMENT ON COLUMN "otp_verifications"."identifier" IS 'email atau nomor telepon';

COMMENT ON COLUMN "otp_verifications"."type" IS 'registration | login | reset_password';

COMMENT ON COLUMN "events"."status" IS 'draft | pending_approval | open | closed | completed | rejected';

COMMENT ON COLUMN "events"."impact_metric_template" IS 'template metrik dampak, cth: kg sampah, jam kontribusi, anak diajar';

COMMENT ON COLUMN "applications"."status" IS 'pending | accepted | rejected | completed';

COMMENT ON COLUMN "applications"."attended" IS 'dikonfirmasi hadir oleh organizer saat tutup event (FR-017 Step 1) — independen dari status';

COMMENT ON COLUMN "applications"."impact_value" IS 'nilai dampak aktual volunteer ini, diisi organizer di FR-017 Step 2';

COMMENT ON COLUMN "impact_logs"."metric_label" IS 'cth: bibit ditanam, sampah diangkat, anak diajar';

COMMENT ON COLUMN "impact_logs"."ai_headline" IS 'narasi pencapaian personal hasil generate AI (FR-024), dibaca FR-009 untuk sertifikat';

COMMENT ON COLUMN "feedbacks"."rating" IS '1-5';

COMMENT ON COLUMN "point_transactions"."amount" IS 'positif = tambah, negatif = kurang';

COMMENT ON COLUMN "point_transactions"."reason" IS 'event_completion | bonus | penalty';

COMMENT ON COLUMN "notifications"."type" IS 'application_accepted | application_rejected | event_completed | system';

COMMENT ON COLUMN "audit_logs"."action" IS 'event.approve | application.accept | user.suspend';

ALTER TABLE "profiles" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "user_skills" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "user_skills" ADD FOREIGN KEY ("skill_id") REFERENCES "skills" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "user_interests" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "user_interests" ADD FOREIGN KEY ("interest_id") REFERENCES "interests" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "events" ADD FOREIGN KEY ("organizer_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "events" ADD FOREIGN KEY ("approved_by") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "event_skills" ADD FOREIGN KEY ("event_id") REFERENCES "events" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "event_skills" ADD FOREIGN KEY ("skill_id") REFERENCES "skills" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "event_interests" ADD FOREIGN KEY ("event_id") REFERENCES "events" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "event_interests" ADD FOREIGN KEY ("interest_id") REFERENCES "interests" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "applications" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "applications" ADD FOREIGN KEY ("event_id") REFERENCES "events" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "applications" ADD CONSTRAINT "applications_user_id_event_id_unique" UNIQUE ("user_id", "event_id");

ALTER TABLE "impact_logs" ADD FOREIGN KEY ("application_id") REFERENCES "applications" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "skill_progress" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "skill_progress" ADD FOREIGN KEY ("skill_id") REFERENCES "skills" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "skill_progress" ADD CONSTRAINT "skill_progress_user_id_skill_id_unique" UNIQUE ("user_id", "skill_id");

ALTER TABLE "feedbacks" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "feedbacks" ADD FOREIGN KEY ("event_id") REFERENCES "events" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "points" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "point_transactions" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "point_transactions" ADD FOREIGN KEY ("event_id") REFERENCES "events" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "certificates" ADD FOREIGN KEY ("application_id") REFERENCES "applications" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "certificates" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "certificates" ADD FOREIGN KEY ("event_id") REFERENCES "events" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "notifications" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "audit_logs" ADD FOREIGN KEY ("actor_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;
