import React from 'react'
import { useLocation } from 'react-router-dom'
import { FiDownloadCloud, FiShare2, FiCalendar } from 'react-icons/fi'

import DashboardView from './reports-views/DashboardView'
import EventAnalyticsView from './reports-views/EventAnalyticsView'
import VolunteerAnalyticsView from './reports-views/VolunteerAnalyticsView'
import ImpactAnalyticsView from './reports-views/ImpactAnalyticsView'
import ExportReportsView from './reports-views/ExportReportsView'

import './ReportsPage.css'

export default function ReportsPage() {
  const location = useLocation()
  const searchParams = new URLSearchParams(location.search)
  const tabParam = searchParams.get('tab')

  const renderView = () => {
    switch (tabParam) {
      case 'event':
        return <EventAnalyticsView />
      case 'volunteer':
        return <VolunteerAnalyticsView />
      case 'impact':
        return <ImpactAnalyticsView />
      case 'export':
        return <ExportReportsView />
      case 'dashboard':
      default:
        return <DashboardView />
    }
  }

  const getTitle = () => {
    switch (tabParam) {
      case 'event': return 'Event Analytics'
      case 'volunteer': return 'Volunteer Analytics'
      case 'impact': return 'Impact Analytics'
      case 'export': return 'Export Reports'
      case 'dashboard': 
      default: return 'Reports & Impact Dashboard'
    }
  }

  const getSubtitle = () => {
    switch (tabParam) {
      case 'event': return 'Analyze event performance, attendance rates, and registration trends.'
      case 'volunteer': return 'Analyze volunteer behavior, demographics, and engagement.'
      case 'impact': return 'Measure social and environmental impact generated by your organization.'
      case 'export': return 'Generate and schedule comprehensive reports for stakeholders.'
      case 'dashboard': 
      default: return 'Monitor overall organization performance, volunteer engagement, and social impact.'
    }
  }

  return (
    <div className="reports-hub">
      {/* Universal Page Header */}
      <header className="reports-header">
        <div className="reports-header__title">
          <h1>{getTitle()}</h1>
          <p className="reports-header__subtitle">{getSubtitle()}</p>
        </div>
        <div className="reports-header__actions">
          {tabParam !== 'export' && (
            <>
              <button type="button" className="btn btn--outline btn--sm"><FiCalendar /> Select Date Range</button>
              <button type="button" className="btn btn--outline btn--sm"><FiShare2 /> Share Dashboard</button>
              <button type="button" className="btn btn--primary btn--sm"><FiDownloadCloud /> Export Report</button>
            </>
          )}
        </div>
      </header>

      {/* Render the contextual content area below the header */}
      {renderView()}
    </div>
  )
}
