import React from 'react'
import { 
  FiFileText, FiDownloadCloud, FiCalendar, FiShare2, FiFile, FiPieChart, FiUsers, FiActivity, FiSettings
} from 'react-icons/fi'
import '../ReportsPage.css'

export default function ExportReportsView() {
  return (
    <>
      {/* KPI Cards */}
      <div className="events-stats-grid" style={{ gridTemplateColumns: 'repeat(4, 1fr)' }}>
        <div className="stat-card">
          <div className="stat-card__icon"><FiFileText /></div>
          <div className="stat-card__value">1,452</div>
          <div className="stat-card__label">Reports Generated</div>
        </div>
        <div className="stat-card">
          <div className="stat-card__icon" style={{ color: 'var(--color-primary)', background: 'var(--color-primary-soft)' }}><FiDownloadCloud /></div>
          <div className="stat-card__value">45</div>
          <div className="stat-card__label">Monthly Exports</div>
        </div>
        <div className="stat-card">
          <div className="stat-card__icon" style={{ color: 'var(--color-warning)', background: '#fffbeb' }}><FiCalendar /></div>
          <div className="stat-card__value">3</div>
          <div className="stat-card__label">Scheduled Reports</div>
        </div>
        <div className="stat-card">
          <div className="stat-card__icon" style={{ color: 'var(--color-success)', background: '#f0fdf4' }}><FiShare2 /></div>
          <div className="stat-card__value">12</div>
          <div className="stat-card__label">Shared Reports</div>
        </div>
      </div>

      <div style={{ display: 'grid', gridTemplateColumns: '2fr 1fr', gap: 'var(--space-xl)', alignItems: 'start' }}>
        {/* Main Content */}
        <div style={{ display: 'flex', flexDirection: 'column', gap: 'var(--space-xl)' }}>
          <section className="card" style={{ padding: '24px' }}>
            <h2 style={{ fontSize: '18px', fontWeight: 600, marginBottom: '20px' }}>Select Report Type</h2>
            
            <div className="export-options-grid">
              <div className="export-card active">
                <FiUsers className="export-card__icon" />
                <div className="export-card__title">Volunteer Report</div>
                <div style={{ fontSize: '11px', color: 'var(--color-text-muted)' }}>Demographics & activity</div>
              </div>
              <div className="export-card">
                <FiActivity className="export-card__icon" style={{ color: 'var(--color-success)' }} />
                <div className="export-card__title">Event Performance</div>
                <div style={{ fontSize: '11px', color: 'var(--color-text-muted)' }}>Attendance & metrics</div>
              </div>
              <div className="export-card">
                <FiPieChart className="export-card__icon" style={{ color: '#f59e0b' }} />
                <div className="export-card__title">Impact Summary</div>
                <div style={{ fontSize: '11px', color: 'var(--color-text-muted)' }}>Social/Environment score</div>
              </div>
              <div className="export-card">
                <FiFile className="export-card__icon" style={{ color: '#8b5cf6' }} />
                <div className="export-card__title">Certificates Log</div>
                <div style={{ fontSize: '11px', color: 'var(--color-text-muted)' }}>Generated certificates</div>
              </div>
            </div>
          </section>

          <section className="card" style={{ padding: '24px' }}>
            <h2 style={{ fontSize: '18px', fontWeight: 600, marginBottom: '20px' }}>Recent Exports</h2>
            <div className="v-table-wrapper">
              <table className="v-table">
                <thead>
                  <tr>
                    <th>Report Type</th>
                    <th>Generated By</th>
                    <th>Date</th>
                    <th>Status</th>
                    <th>Action</th>
                  </tr>
                </thead>
                <tbody>
                  <tr>
                    <td style={{ fontWeight: 600 }}><FiUsers style={{ marginRight: '8px', color: 'var(--color-text-muted)' }} /> Volunteer Summary</td>
                    <td>Emma</td>
                    <td>Today, 10:00 AM</td>
                    <td><span className="badge badge--success">Completed</span></td>
                    <td><button className="btn btn--sm btn--primary"><FiDownloadCloud /> Download</button></td>
                  </tr>
                  <tr>
                    <td style={{ fontWeight: 600 }}><FiActivity style={{ marginRight: '8px', color: 'var(--color-text-muted)' }} /> Attendance Report</td>
                    <td>Sophia</td>
                    <td>Yesterday</td>
                    <td><span className="badge badge--success">Completed</span></td>
                    <td><button className="btn btn--sm btn--primary"><FiDownloadCloud /> Download</button></td>
                  </tr>
                  <tr>
                    <td style={{ fontWeight: 600 }}><FiPieChart style={{ marginRight: '8px', color: 'var(--color-text-muted)' }} /> Q2 Impact Report</td>
                    <td>Noah</td>
                    <td>Monday</td>
                    <td><span className="badge badge--success">Completed</span></td>
                    <td><button className="btn btn--sm btn--primary"><FiDownloadCloud /> Download</button></td>
                  </tr>
                </tbody>
              </table>
            </div>
          </section>
        </div>

        {/* Side Form */}
        <section className="card" style={{ padding: '24px', position: 'sticky', top: '24px' }}>
          <h2 style={{ fontSize: '16px', fontWeight: 600, marginBottom: '20px', display: 'flex', alignItems: 'center', gap: '8px' }}>
            <FiSettings /> Report Settings
          </h2>
          
          <div className="export-settings-group">
            <label>Date Range</label>
            <select>
              <option>Last 30 Days</option>
              <option>This Quarter</option>
              <option>This Year</option>
              <option>Custom Range</option>
            </select>
          </div>

          <div className="export-settings-group">
            <label>Event Category Filter</label>
            <select>
              <option>All Categories</option>
              <option>Environment</option>
              <option>Education</option>
              <option>Health</option>
            </select>
          </div>

          <div className="export-settings-group">
            <label>Format</label>
            <div style={{ display: 'flex', gap: '12px' }}>
              <label style={{ display: 'flex', alignItems: 'center', gap: '6px', fontSize: '13px', fontWeight: 400 }}><input type="radio" name="fmt" defaultChecked /> PDF</label>
              <label style={{ display: 'flex', alignItems: 'center', gap: '6px', fontSize: '13px', fontWeight: 400 }}><input type="radio" name="fmt" /> Excel</label>
              <label style={{ display: 'flex', alignItems: 'center', gap: '6px', fontSize: '13px', fontWeight: 400 }}><input type="radio" name="fmt" /> CSV</label>
            </div>
          </div>

          <div className="export-settings-group">
            <label>Schedule Delivery (Optional)</label>
            <select>
              <option>Generate Once (Now)</option>
              <option>Weekly (Every Monday)</option>
              <option>Monthly (1st of Month)</option>
            </select>
          </div>

          <button className="btn btn--primary" style={{ width: '100%', marginTop: '12px', display: 'flex', justifyContent: 'center', alignItems: 'center', gap: '8px' }}>
            <FiDownloadCloud /> Generate Report
          </button>
        </section>
      </div>
    </>
  )
}
