// Data event DUMMY untuk sistem rekomendasi (FR-005) — dipakai sementara sampai
// listing Event PUBLISHED di database punya tag skill/interest yang di-seed.
// Bentuk field disamakan dengan frontend/src/data/mockEvents.ts (types/event.ts)
// supaya card di dashboard bisa langsung dirender dari response API, plus field
// tagging tambahan yang dibutuhkan algoritma matching:
//   - skills / interests : dicocokkan by-name (case-insensitive) ke UserSkill/UserInterest
//   - motivationTags     : nilai enum Motivation (CAREER|SOCIAL|VALUES|SKILL_GROWTH)
//   - dayType            : WEEKDAY | WEEKEND | BOTH — dicocokkan ke Profile.availability
//   - symbol             : kunci ikon default per kategori (bisa dioverride hasil AI)

export const CATEGORY_SYMBOLS = {
  Lingkungan: '🌱',
  Pendidikan: '📚',
  Kesehatan: '❤️',
  Sosial: '🤝',
  Teknologi: '💻',
  'Seni & Budaya': '🎨',
}

export const DUMMY_EVENTS = [
  {
    id: 'dummy-evt-1',
    title: 'Bersih Pantai Parangtritis',
    description:
      'Aksi bersih-bersih sampah plastik di sepanjang Pantai Parangtritis bersama komunitas pesisir, dilanjutkan edukasi pengelolaan sampah untuk warga sekitar.',
    category: 'Lingkungan',
    location: 'Parangtritis, Bantul',
    organizerName: 'Komunitas Laut Lestari',
    quota: 30,
    filledSlots: 22,
    startDate: '2026-07-12',
    endDate: '2026-07-12',
    skills: ['Kerja Tim', 'Fisik/Lapangan', 'Edukasi Publik'],
    interests: ['Lingkungan', 'Kelautan', 'Komunitas'],
    motivationTags: ['VALUES', 'SOCIAL'],
    dayType: 'WEEKEND',
    symbol: CATEGORY_SYMBOLS.Lingkungan,
  },
  {
    id: 'dummy-evt-2',
    title: 'Mengajar Baca Tulis Anak Pesisir',
    description:
      'Program belajar baca-tulis untuk anak-anak nelayan di pesisir selatan Gunungkidul, 2 jam tiap akhir pekan selama satu bulan.',
    category: 'Pendidikan',
    location: 'Tepus, Gunungkidul',
    organizerName: 'Yayasan Cahaya Pesisir',
    quota: 15,
    filledSlots: 9,
    startDate: '2026-07-18',
    endDate: '2026-08-09',
    skills: ['Mengajar', 'Kesabaran', 'Komunikasi'],
    interests: ['Pendidikan', 'Anak-anak', 'Literasi'],
    motivationTags: ['VALUES', 'SKILL_GROWTH'],
    dayType: 'WEEKEND',
    symbol: CATEGORY_SYMBOLS.Pendidikan,
  },
  {
    id: 'dummy-evt-3',
    title: 'Posko Kesehatan Gratis Lansia',
    description:
      'Membantu tenaga medis melayani pemeriksaan kesehatan gratis untuk lansia di balai desa: registrasi, pendampingan antre, dan pencatatan hasil pemeriksaan.',
    category: 'Kesehatan',
    location: 'Sleman, Yogyakarta',
    organizerName: 'Relawan Sehat Nusantara',
    quota: 20,
    filledSlots: 11,
    startDate: '2026-07-15',
    endDate: '2026-07-16',
    skills: ['Administrasi', 'Komunikasi', 'Empati'],
    interests: ['Kesehatan', 'Lansia', 'Komunitas'],
    motivationTags: ['VALUES', 'CAREER'],
    dayType: 'WEEKDAY',
    symbol: CATEGORY_SYMBOLS.Kesehatan,
  },
  {
    id: 'dummy-evt-4',
    title: 'Dapur Umum Peduli Banjir',
    description:
      'Menyiapkan dan mendistribusikan makanan siap saji untuk warga terdampak banjir. Dibutuhkan tenaga masak, packing, dan distribusi logistik.',
    category: 'Sosial',
    location: 'Semarang, Jawa Tengah',
    organizerName: 'Aksi Cepat Peduli',
    quota: 40,
    filledSlots: 31,
    startDate: '2026-07-10',
    endDate: '2026-07-14',
    skills: ['Kerja Tim', 'Fisik/Lapangan', 'Logistik'],
    interests: ['Kemanusiaan', 'Tanggap Bencana', 'Komunitas'],
    motivationTags: ['SOCIAL', 'VALUES'],
    dayType: 'BOTH',
    symbol: CATEGORY_SYMBOLS.Sosial,
  },
  {
    id: 'dummy-evt-5',
    title: 'Kelas Coding Dasar untuk Remaja Panti',
    description:
      'Mengajarkan dasar-dasar pemrograman web (HTML/CSS/JavaScript) kepada remaja panti asuhan selama 4 sesi akhir pekan, kurikulum sudah disiapkan.',
    category: 'Teknologi',
    location: 'Kota Yogyakarta',
    organizerName: 'CodeForGood ID',
    quota: 10,
    filledSlots: 4,
    startDate: '2026-07-19',
    endDate: '2026-08-10',
    skills: ['Programming', 'Mengajar', 'Komunikasi'],
    interests: ['Teknologi', 'Pendidikan', 'Anak-anak'],
    motivationTags: ['SKILL_GROWTH', 'CAREER'],
    dayType: 'WEEKEND',
    symbol: CATEGORY_SYMBOLS.Teknologi,
  },
  {
    id: 'dummy-evt-6',
    title: 'Festival Seni Difabel Berdaya',
    description:
      'Menjadi pendamping peserta difabel dan kru acara di festival seni tahunan: dokumentasi, dekorasi panggung, dan pendampingan penampil.',
    category: 'Seni & Budaya',
    location: 'Kota Yogyakarta',
    organizerName: 'Sanggar Inklusi Budaya',
    quota: 25,
    filledSlots: 12,
    startDate: '2026-07-25',
    endDate: '2026-07-26',
    skills: ['Desain/Dokumentasi', 'Empati', 'Kerja Tim'],
    interests: ['Seni & Budaya', 'Difabel', 'Komunitas'],
    motivationTags: ['SOCIAL', 'VALUES'],
    dayType: 'WEEKEND',
    symbol: CATEGORY_SYMBOLS['Seni & Budaya'],
  },
  {
    id: 'dummy-evt-7',
    title: 'Penanaman 1000 Mangrove',
    description:
      'Penanaman bibit mangrove di kawasan konservasi pesisir Kulon Progo bersama kelompok tani hutan, termasuk edukasi singkat ekosistem pesisir.',
    category: 'Lingkungan',
    location: 'Kulon Progo, Yogyakarta',
    organizerName: 'Green Coast Initiative',
    quota: 50,
    filledSlots: 27,
    startDate: '2026-08-02',
    endDate: '2026-08-02',
    skills: ['Fisik/Lapangan', 'Kerja Tim'],
    interests: ['Lingkungan', 'Konservasi', 'Kelautan'],
    motivationTags: ['VALUES'],
    dayType: 'WEEKEND',
    symbol: CATEGORY_SYMBOLS.Lingkungan,
  },
  {
    id: 'dummy-evt-8',
    title: 'Pendampingan UMKM Go-Digital',
    description:
      'Mendampingi pelaku UMKM pasar tradisional membuat katalog online dan mengelola media sosial usaha mereka, sesi fleksibel di hari kerja.',
    category: 'Teknologi',
    location: 'Bantul, Yogyakarta',
    organizerName: 'Digitalisasi Desa',
    quota: 12,
    filledSlots: 5,
    startDate: '2026-07-21',
    endDate: '2026-08-21',
    skills: ['Digital Marketing', 'Komunikasi', 'Desain/Dokumentasi'],
    interests: ['Teknologi', 'Ekonomi Kreatif', 'Komunitas'],
    motivationTags: ['CAREER', 'SKILL_GROWTH'],
    dayType: 'WEEKDAY',
    symbol: CATEGORY_SYMBOLS.Teknologi,
  },
]
